//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class pract_voprs
    {
        public int id { get; set; }
        public int id_predmet { get; set; }
        public string pr_vopr { get; set; }
    
        public virtual predmets predmets { get; set; }
    }
}
