//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string fio { get; set; }
        public string login { get; set; }
        public string parol { get; set; }
        public int id_rol { get; set; }
        public int id_predmet { get; set; }
    
        public virtual predmets predmets { get; set; }
        public virtual rols rols { get; set; }
    }
}
